version: 3.0.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
image: Visual Studio 2017
before_build:
  - ps: dotnet restore --no-cache --verbosity=normal
build_script:
  - ps: dotnet build --no-restore --configuration="release" -p:Version="$env:APPVEYOR_BUILD_VERSION"
after_build:
  - ps: dotnet pack Grumpy.DacpacMerge/Grumpy.DacpacMerge.csproj --no-build --include-symbols --include-source --verbosity=normal -p:PackageVersion="$env:APPVEYOR_BUILD_VERSION" --configuration="release"
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.7.922\\tools\\OpenCover.Console.exe\" -register:user -oldStyle -target:\"%ProgramFiles%\\dotnet\\dotnet.exe\" -targetargs:\"test Grumpy.Common.UnitTests\\Grumpy.DacpacMerge.UnitTests.csproj\" -output:\"coverage.xml\" -filter:\"+[Grumpy.DacpacMerge*]* -[Grumpy.DacpacMerge.UnitTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 502e368a-6011-4c87-9f61-e67cc5a9b6ac
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: Environment
  name: NuGet
