version: 0.9.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.DacpacMerge.UnitTests\\bin\\Release\\Grumpy.DacpacMerge.UnitTests.dll Grumpy.DacpacMerge.IntegrationTests\\bin\\Release\\Grumpy.DacpacMerge.IntegrationTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.DacpacMerge*]* -[Grumpy.DacpacMerge.UnitTests*] -[Grumpy.DacpacMerge.IntegrationTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 502e368a-6011-4c87-9f61-e67cc5a9b6ac
after_build:
  - ps: nuget pack Grumpy.DacpacMerge\bin\Release\Grumpy.DacpacMerge.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: EqocuRN+dPLo43f6XC9SZIry4fYwoAibK7wTAte9Rrbc4Xl/OyWhGo75yv3/Rs+/
  skip_symbols: false
  artifact: /.*\.nupkg/
